name: Sentinel-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Validate Wazuh Rules
        run: |
          xmllint --noout wazuh/rules/local_rules.xml
          echo "XML Syntax is valid."